export enum Names {
  AUTH = 'auth',
  AUTH_LOGIN = 'auth-login',
  AUTH_LOGOUT = 'auth-logout',
  AUTH_REGISTER = 'auth-register',
  AUTH_FORGOT = 'auth-forgot',
  MAIN = 'main',
  PROFILE = 'profile',
  ACCOUNT = 'account',
  PASSWORD = 'password',
  EMAIL = 'email',
  PLACES = 'places',
  PLACES_LIST = 'places-list',
  PLACES_ADD = 'places-add',
  PLACES_DETAILS = 'places-details',
  ROUTES = 'routes',
  ROUTES_LIST = 'routes-list',
  ROUTES_ADD = 'routes-add',
  ROUTES_DETAILS = 'routes-details',
  VIEWER = 'viewer',
  ABOUT = 'about',
  ERROR = 'error',
}

export enum Paths {
  AUTH = 'auth',
  AUTH_LOGIN = 'login',
  AUTH_REGISTER = 'register',
  AUTH_FORGOT = 'forgot',
  AUTH_LOGOUT = 'logout',
  MAIN = '/app',
  PROFILE = 'profile',
  ACCOUNT = 'account',
  PASSWORD = 'password',
  EMAIL = 'email',
  PLACES = 'places',
  PLACES_LIST = 'list',
  PLACES_ADD = 'add',
  PLACES_DETAILS = ':id',
  ROUTES = 'routes',
  ROUTES_LIST = 'list',
  ROUTES_ADD = 'add',
  ROUTES_DETAILS = ':id',
  VIEWER = 'viewer',
  ABOUT = '/',
  ERROR = '/:pathMatch(.*)*',
}
